spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/board_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: board_user
#    password: '0000'
    # H2 DB 설정
  datasource:
    url: jdbc:h2:mem:boarddb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB   # 개별 파일의 최대 크기
      max-request-size: 50MB # 한 번의 요청에 포함된 모든 파일의 총 크기

  custom:
    upload:
      path: C:/codes/board

  # H2
  h2:
    console:
      enabled: true
      # h2-console 접속 경로 설정 (옵션)
      path: /h2-console

  sql:
    init:
      mode: always



server:
  port: 8080
